[agent]
  interval = "15s"
  hostname = "ubuntu-server"

# Read metrics from the Docker API
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"
  perdevice = true
  total = false

# Read metrics from the Ubuntu Host Hardware
[[inputs.cpu]]
  percpu = true
  totalcpu = true
[[inputs.mem]]
[[inputs.disk]]
[[inputs.system]]

# Expose metrics for Prometheus to scrape
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2